version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=koteika322
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: sportique_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443-443'
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=koteika322
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - psql-db
    volumes:
      - logs:/logs

volumes:
  db-data:
  logs: